In [ ]:
import numpy as np

In [ ]:
class NeuralNet:
  def __init__(self, input_nodes):
    self.n = input_nodes
    self.w = np.zeros((self.n))
    self.b = 0

  def __train(self, x, y):
    self.w += np.array(x) * y
    self.b += y

  def fit(self, X, y):
    assert len(X[0]) == self.n, "Invalid input shape."
    for i in range(len(X)):
      self.__train(X[i], y[i])

  def predict(self, X):
    return np.sum(self.w * X, axis = 1) + self.b

OR GATE

In [ ]:
or_model = NeuralNet(2)

In [ ]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [-1, 1, 1, 1]

In [ ]:
or_model.fit(X, y)

In [ ]:
or_model.w
or_model.b

2

In [ ]:
or_model.predict(X)

array([-2.,  2.,  2.,  6.])

AND GATE

In [ ]:
and_model = NeuralNet(2)

In [ ]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [-1, -1, -1, 1]

In [ ]:
and_model.fit(X, y)

In [ ]:
and_model.w
and_model.b

-2

In [ ]:
and_model.predict(X)

array([-6., -2., -2.,  2.])

NOT GATE

In [ ]:
not_model = NeuralNet(1)

In [ ]:
X = [
     [-1],
     [1]
]
y = [1, -1]

In [ ]:
not_model.fit(X, y)

In [ ]:
not_model.w, not_model.b

(array([-2.]), 0)

In [ ]:
not_model.predict(X)

array([ 2., -2.])

NOR GATE

In [ ]:
nor_model = NeuralNet(2)

In [ ]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [1, -1, -1, -1]

In [ ]:
nor_model.fit(X, y)

In [ ]:
nor_model.w, nor_model.b

(array([-2., -2.]), -2)

In [ ]:
nor_model.predict(X)

array([ 2., -2., -2., -6.])

NAND GATE

In [ ]:
nand_model = NeuralNet(2)

In [ ]:
X = [
     [-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]
]
y = [1, 1, 1, -1]

In [ ]:
nand_model.fit(X, y)

In [ ]:
nand_model.predict(X)

array([ 6.,  2.,  2., -2.])